export const colors = {
  action: {
    primary: "#38E33C",
    primaryPressed: "#2FC933",
    onPrimary: "#000000",

    onSecondary: "#020617",

    onGhost: "#0F172A",
    ghostPressed: "#F1F5F9",

    destructive: "#EF4444",
    destructivePressed: "#DC2626",
    onDestructive: "#FFFFFF",

    disabled: "#E2E8F0",
    onDisabled: "#94A3B8",
  },
  text: {
    primary: "#0F172A",
    secondary: "#475569",
    tertiary: "#64748B",
    disabled: "#94A3B8",
  },
  background: {
    surface: "#FFFFFF",
    muted: "#F1F5F9",
    accentSubtle: "#F7EBDA",
  },
  border: {
    default: "#E2E8F0",
    strong: "#CBD5E1",
    focus: "#38E33C",
    error: "#EF4444",
  },
  feedback: {
    error: "#B91C1C",
    errorBg: "#FEF2F2",
    successBg: "#ECFDEC",
    successFg: "#239626",
    infoBg: "#EFF6FF",
    infoFg: "#1D4ED8",
    warningBg: "#FFFBEB",
    warningFg: "#B45309",
  },
  surface: "#FFFFFF",
  surfaceMuted: "#F3F4F6",
  textMuted: "#6B7280",
  borderLegacy: "#E5E7EB",
} as const;

export const spacing = {
  xxxs: 2,
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 32,
} as const;

export const radii = {
  xs: 2,
  control: 4,
  sm: 8,
  md: 12,
  lg: 12,
  xl: 16,
  full: 9999,
} as const;

export const fontFamily = {
  poppinsRegular: "Poppins_400Regular",
  poppinsMedium: "Poppins_500Medium",
  poppinsSemiBold: "Poppins_600SemiBold",
  poppinsBold: "Poppins_700Bold",
} as const;

export const typography = {
  displayLarge: {
    fontFamily: fontFamily.poppinsBold,
    fontSize: 36,
    lineHeight: 44,
    fontWeight: "700" as const,
    letterSpacing: -0.36,
  },
  headingH1: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "600" as const,
    letterSpacing: -0.168,
  },
  headingH2: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "600" as const,
    letterSpacing: -0.088,
  },
  headingH3: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "600" as const,
    letterSpacing: -0.036,
  },
  titleDefault: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500" as const,
    letterSpacing: 0,
  },
  titleSmall: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
    letterSpacing: 0,
  },
  bodyLarge: {
    fontFamily: fontFamily.poppinsRegular,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  bodyDefault: {
    fontFamily: fontFamily.poppinsRegular,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  bodySmall: {
    fontFamily: fontFamily.poppinsRegular,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "400" as const,
    letterSpacing: 0.024,
  },
  labelDefault: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
    letterSpacing: 0.028,
  },
  labelSmall: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500" as const,
    letterSpacing: 0.048,
  },
  buttonMd: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600" as const,
    letterSpacing: 0.056,
  },
  buttonSm: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "600" as const,
    letterSpacing: 0.072,
  },
  buttonLg: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600" as const,
    letterSpacing: 0.4,
  },
  caption: {
    fontFamily: fontFamily.poppinsRegular,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "400" as const,
    letterSpacing: 0.044,
  },
  overline: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 10,
    lineHeight: 16,
    fontWeight: "600" as const,
    letterSpacing: 1.5,
  },
  chipLabel: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500" as const,
    letterSpacing: 0.026,
  },
  badgeLabel: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 11,
    lineHeight: 11,
    fontWeight: "600" as const,
    letterSpacing: 0.044,
  },
  avatarInitials: {
    fontFamily: fontFamily.poppinsSemiBold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600" as const,
    letterSpacing: 0,
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "400" as const,
  },
} as const;

export const controlSize = {
  sm: 32,
  md: 40,
  lg: 48,
  textField: 120,
  radio: 20,
  checkbox: 20,
  switchWidth: 44,
  switchHeight: 24,
  switchThumb: 20,
  snackbar: 56,
  appBar: 56,
  badgeDot: 10,
  badgeCount: 18,
  modalWidth: 320,
  modalMinHeight: 240,
  modalIcon: 48,
  stepperHeight: 6,
  stepperDot: 6,
  stepperActiveWidth: 24,
  mediaCardWidth: 320,
  bannerCardWidth: 360,
  mediaCardImageHeight: 120,
  actionTileIcon: 40,
  actionTileVerticalWidth: 160,
  actionTileHorizontalWidth: 360,
  listAvatar: 40,
  avatarSm: 32,
  avatarMd: 40,
  avatarLg: 56,
  avatarXl: 80,
} as const;

export const iconSize = {
  sm: 16,
  md: 20,
  lg: 24,
} as const;
